version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /nexus
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /schema-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /nexus
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /schema-service
    schedule:
      interval: weekly
