-- Enhancement to Query History Table
-- Adds support for:
-- - User-provided query names
-- - Chart recommendations from LLM
-- - LLM response time tracking
-- - Separate generation and execution timestamps
-- - Query type (natural language vs manual SQL)

SET search_path TO nexus, public;

-- Add new columns to query_history table
ALTER TABLE nexus.query_history 
  ADD COLUMN IF NOT EXISTS query_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS query_type VARCHAR(20) DEFAULT 'natural_language' CHECK (query_type IN ('natural_language', 'manual')),
  ADD COLUMN IF NOT EXISTS chart_recommendation JSONB,
  ADD COLUMN IF NOT EXISTS llm_response_time_ms INTEGER,
  ADD COLUMN IF NOT EXISTS generated_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS executed_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add comments for documentation
COMMENT ON COLUMN nexus.query_history.query_name IS 'User-provided name for the query (optional, can be set/updated later)';
COMMENT ON COLUMN nexus.query_history.query_type IS 'Type of query: natural_language (NL->SQL with LLM) or manual (direct SQL)';
COMMENT ON COLUMN nexus.query_history.chart_recommendation IS 'LLM chart recommendation: {chart_type, x_column, y_column, title, etc.}';
COMMENT ON COLUMN nexus.query_history.llm_response_time_ms IS 'Time taken by LLM to generate SQL (milliseconds)';
COMMENT ON COLUMN nexus.query_history.generated_at IS 'Timestamp when SQL was generated by LLM or entered manually';
COMMENT ON COLUMN nexus.query_history.executed_at IS 'Timestamp when SQL was executed against Trino';
COMMENT ON COLUMN nexus.query_history.execution_time_ms IS 'Time taken to execute SQL query in Trino (milliseconds)';

-- Backfill generated_at and executed_at for existing records
UPDATE nexus.query_history 
SET 
  generated_at = COALESCE(generated_at, created_at),
  executed_at = COALESCE(executed_at, created_at)
WHERE generated_at IS NULL OR executed_at IS NULL;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_query_history_query_type ON nexus.query_history(query_type);
CREATE INDEX IF NOT EXISTS idx_query_history_generated_at ON nexus.query_history(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_query_history_executed_at ON nexus.query_history(executed_at DESC);
CREATE INDEX IF NOT EXISTS idx_query_history_user_generated ON nexus.query_history(user_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_query_history_query_name ON nexus.query_history(query_name) WHERE query_name IS NOT NULL;

-- Add trigger for updated_at
DROP TRIGGER IF EXISTS set_timestamp_query_history ON nexus.query_history;
CREATE TRIGGER set_timestamp_query_history 
  BEFORE UPDATE ON nexus.query_history 
  FOR EACH ROW 
  EXECUTE PROCEDURE nexus.trigger_set_timestamp();

-- Create a view for easy querying with user details
CREATE OR REPLACE VIEW nexus.query_history_with_users AS
SELECT 
  qh.id,
  qh.user_id,
  u.username,
  u.email,
  u.full_name,
  qh.session_id,
  qh.query_name,
  qh.query_type,
  qh.natural_language_query,
  qh.generated_sql,
  qh.execution_status,
  qh.execution_time_ms,
  qh.llm_response_time_ms,
  qh.row_count,
  qh.error_message,
  qh.chart_recommendation,
  qh.schema_recommendations,
  qh.model_confidence,
  qh.retry_attempts,
  qh.generated_at,
  qh.executed_at,
  qh.created_at,
  qh.updated_at
FROM nexus.query_history qh
LEFT JOIN nexus.users u ON qh.user_id = u.id;

-- Grant access to the view
GRANT SELECT ON nexus.query_history_with_users TO nexus_service;

-- Create a helper function to generate query title for manual queries
CREATE OR REPLACE FUNCTION nexus.generate_query_title(sql_text TEXT) 
RETURNS VARCHAR(255) AS $$
DECLARE
  title VARCHAR(255);
  table_name TEXT;
BEGIN
  -- Extract first table name from SQL
  SELECT regexp_replace(
    substring(sql_text FROM 'FROM\s+([a-zA-Z0-9_.]+)'),
    '^[a-zA-Z0-9_]+\.',
    ''
  ) INTO table_name;
  
  -- Generate title based on SQL operation
  IF sql_text ~* '^\s*SELECT' THEN
    IF sql_text ~* '\bCOUNT\(' THEN
      title := 'Count from ' || COALESCE(table_name, 'table');
    ELSIF sql_text ~* '\bSUM\(' THEN
      title := 'Sum from ' || COALESCE(table_name, 'table');
    ELSIF sql_text ~* '\bAVG\(' THEN
      title := 'Average from ' || COALESCE(table_name, 'table');
    ELSIF sql_text ~* '\bMAX\(|\bMIN\(' THEN
      title := 'Aggregate from ' || COALESCE(table_name, 'table');
    ELSIF sql_text ~* '\bGROUP BY\b' THEN
      title := 'Group by from ' || COALESCE(table_name, 'table');
    ELSE
      title := 'Query from ' || COALESCE(table_name, 'table');
    END IF;
  ELSIF sql_text ~* '^\s*INSERT' THEN
    title := 'Insert into ' || COALESCE(table_name, 'table');
  ELSIF sql_text ~* '^\s*UPDATE' THEN
    title := 'Update ' || COALESCE(table_name, 'table');
  ELSIF sql_text ~* '^\s*DELETE' THEN
    title := 'Delete from ' || COALESCE(table_name, 'table');
  ELSE
    title := 'SQL Query';
  END IF;
  
  RETURN title;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Example: Update query_name for manual queries without a name
UPDATE nexus.query_history 
SET query_name = nexus.generate_query_title(generated_sql)
WHERE query_type = 'manual' 
  AND query_name IS NULL 
  AND generated_sql IS NOT NULL;

COMMENT ON FUNCTION nexus.generate_query_title(TEXT) IS 'Auto-generates a descriptive title for SQL queries based on operation and table';

-- Create an API-friendly view for the frontend
CREATE OR REPLACE VIEW nexus.query_history_summary AS
SELECT 
  id,
  user_id,
  query_name,
  query_type,
  CASE 
    WHEN LENGTH(natural_language_query) > 100 THEN LEFT(natural_language_query, 100) || '...'
    ELSE natural_language_query
  END as nl_query_preview,
  CASE 
    WHEN LENGTH(generated_sql) > 200 THEN LEFT(generated_sql, 200) || '...'
    ELSE generated_sql
  END as sql_preview,
  execution_status,
  execution_time_ms,
  llm_response_time_ms,
  row_count,
  chart_recommendation->>'chart_type' as chart_type,
  generated_at,
  executed_at,
  created_at
FROM nexus.query_history
ORDER BY executed_at DESC;

GRANT SELECT ON nexus.query_history_summary TO nexus_service;

COMMENT ON VIEW nexus.query_history_summary IS 'Lightweight view of query history for listing/search without full SQL text';

