-- Dashboard Tiles and RBAC Enhancement
-- Creates a proper dashboard system with:
-- 1. Dashboard tiles (individual charts/widgets)
-- 2. RBAC permissions (view, edit, delete, share)
-- 3. Support for all Plotly.js chart types

SET search_path TO nexus, public;

-- =============================================================================
-- 1. DASHBOARD TILES TABLE
-- =============================================================================
-- Each dashboard can have multiple tiles (charts/widgets)

CREATE TABLE IF NOT EXISTS nexus.dashboard_tiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dashboard_id UUID NOT NULL REFERENCES nexus.dashboards(id) ON DELETE CASCADE,
    
    -- Tile Content
    title VARCHAR(200) NOT NULL,
    description TEXT,
    
    -- Query Configuration
    sql_query TEXT NOT NULL,
    natural_language_query TEXT, -- Original NL query if generated by AI
    
    -- Chart Configuration
    chart_type VARCHAR(50) NOT NULL DEFAULT 'bar',
    chart_config JSONB, -- Plotly-specific config (colors, axes, etc.)
    
    -- Layout & Display
    position_x INTEGER NOT NULL DEFAULT 0, -- Grid position X
    position_y INTEGER NOT NULL DEFAULT 0, -- Grid position Y
    width INTEGER NOT NULL DEFAULT 6, -- Grid width (1-12)
    height INTEGER NOT NULL DEFAULT 4, -- Grid height
    
    -- Data Refresh
    refresh_interval_seconds INTEGER, -- Auto-refresh interval (null = manual only)
    last_refreshed_at TIMESTAMP,
    
    -- Metadata
    created_by UUID REFERENCES nexus.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT valid_chart_type CHECK (chart_type IN (
        -- Basic Charts
        'bar', 'line', 'scatter', 'pie', 'donut',
        -- Statistical Charts
        'box', 'violin', 'histogram', 'histogram2d',
        -- 3D Charts
        'scatter3d', 'line3d', 'surface', 'mesh3d',
        -- Financial Charts
        'candlestick', 'ohlc', 'waterfall', 'funnel',
        -- Maps & Geo
        'scattergeo', 'choropleth', 'scattermapbox',
        -- Specialized
        'heatmap', 'contour', 'sankey', 'sunburst', 'treemap',
        'parallel', 'parcoords', 'table', 'indicator',
        -- Multi-series
        'area', 'stackedbar', 'groupedbar', 'bubble'
    )),
    CONSTRAINT valid_grid_position CHECK (position_x >= 0 AND position_y >= 0),
    CONSTRAINT valid_grid_size CHECK (width BETWEEN 1 AND 12 AND height >= 1)
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_dashboard_tiles_dashboard_id ON nexus.dashboard_tiles(dashboard_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_tiles_created_by ON nexus.dashboard_tiles(created_by);
CREATE INDEX IF NOT EXISTS idx_dashboard_tiles_chart_type ON nexus.dashboard_tiles(chart_type);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS set_timestamp_dashboard_tiles ON nexus.dashboard_tiles;
CREATE TRIGGER set_timestamp_dashboard_tiles 
    BEFORE UPDATE ON nexus.dashboard_tiles 
    FOR EACH ROW 
    EXECUTE PROCEDURE nexus.trigger_set_timestamp();

-- =============================================================================
-- 2. DASHBOARD PERMISSIONS TABLE (RBAC)
-- =============================================================================
-- Fine-grained access control for dashboards

CREATE TABLE IF NOT EXISTS nexus.dashboard_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dashboard_id UUID NOT NULL REFERENCES nexus.dashboards(id) ON DELETE CASCADE,
    
    -- Target (either user or group, not both)
    user_id UUID REFERENCES nexus.users(id) ON DELETE CASCADE,
    group_id UUID REFERENCES nexus.groups(id) ON DELETE CASCADE,
    
    -- Permissions (granular control)
    can_view BOOLEAN NOT NULL DEFAULT TRUE,
    can_edit BOOLEAN NOT NULL DEFAULT FALSE,
    can_delete BOOLEAN NOT NULL DEFAULT FALSE,
    can_share BOOLEAN NOT NULL DEFAULT FALSE, -- Can grant permissions to others
    
    -- Metadata
    granted_by UUID REFERENCES nexus.users(id) ON DELETE SET NULL, -- Who granted this permission
    granted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP, -- Optional expiration for temporary access
    
    -- Constraints
    CONSTRAINT either_user_or_group CHECK (
        (user_id IS NOT NULL AND group_id IS NULL) OR 
        (user_id IS NULL AND group_id IS NOT NULL)
    ),
    CONSTRAINT at_least_one_permission CHECK (
        can_view OR can_edit OR can_delete OR can_share
    ),
    -- Unique constraint: one permission record per user/group per dashboard
    CONSTRAINT unique_dashboard_user_permission UNIQUE (dashboard_id, user_id),
    CONSTRAINT unique_dashboard_group_permission UNIQUE (dashboard_id, group_id)
);

-- Indexes for efficient permission checks
CREATE INDEX IF NOT EXISTS idx_dashboard_permissions_dashboard ON nexus.dashboard_permissions(dashboard_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_permissions_user ON nexus.dashboard_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_permissions_group ON nexus.dashboard_permissions(group_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_permissions_expires ON nexus.dashboard_permissions(expires_at) WHERE expires_at IS NOT NULL;

-- =============================================================================
-- 3. ENHANCE DASHBOARDS TABLE
-- =============================================================================
-- Add missing fields to existing dashboards table

-- Add layout configuration for grid system
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'nexus' 
        AND table_name = 'dashboards' 
        AND column_name = 'layout_config'
    ) THEN
        ALTER TABLE nexus.dashboards 
        ADD COLUMN layout_config JSONB DEFAULT '{"columns": 12, "rowHeight": 100, "compactType": "vertical"}'::jsonb;
    END IF;
END $$;

-- Add dashboard tags for organization
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'nexus' 
        AND table_name = 'dashboards' 
        AND column_name = 'tags'
    ) THEN
        ALTER TABLE nexus.dashboards ADD COLUMN tags JSONB DEFAULT '[]'::jsonb;
    END IF;
END $$;

-- Add is_favorite flag
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'nexus' 
        AND table_name = 'dashboards' 
        AND column_name = 'is_favorite'
    ) THEN
        ALTER TABLE nexus.dashboards ADD COLUMN is_favorite BOOLEAN DEFAULT FALSE;
    END IF;
END $$;

-- Add last_accessed_at for analytics
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'nexus' 
        AND table_name = 'dashboards' 
        AND column_name = 'last_accessed_at'
    ) THEN
        ALTER TABLE nexus.dashboards ADD COLUMN last_accessed_at TIMESTAMP;
    END IF;
END $$;

-- =============================================================================
-- 4. RBAC HELPER FUNCTIONS
-- =============================================================================

-- Function: Check if user has specific permission on dashboard
CREATE OR REPLACE FUNCTION nexus.user_has_dashboard_permission(
    p_user_id UUID,
    p_dashboard_id UUID,
    p_permission VARCHAR -- 'view', 'edit', 'delete', 'share'
) RETURNS BOOLEAN AS $$
DECLARE
    is_owner BOOLEAN;
    has_direct_permission BOOLEAN;
    has_group_permission BOOLEAN;
    is_admin BOOLEAN;
BEGIN
    -- 1. Check if user is owner (owners have all permissions)
    SELECT EXISTS (
        SELECT 1 FROM nexus.dashboards 
        WHERE id = p_dashboard_id AND owner_user_id = p_user_id
    ) INTO is_owner;
    
    IF is_owner THEN
        RETURN TRUE;
    END IF;
    
    -- 2. Check if user is ADMIN or SUPERADMIN (admins have all permissions)
    SELECT EXISTS (
        SELECT 1 FROM nexus.user_roles ur
        JOIN nexus.roles r ON ur.role_id = r.id
        WHERE ur.user_id = p_user_id 
        AND LOWER(r.name) IN ('admin', 'superadmin')
    ) INTO is_admin;
    
    IF is_admin THEN
        RETURN TRUE;
    END IF;
    
    -- 3. Check if dashboard is public and permission is 'view'
    IF p_permission = 'view' THEN
        IF EXISTS (
            SELECT 1 FROM nexus.dashboards 
            WHERE id = p_dashboard_id AND is_public = TRUE
        ) THEN
            RETURN TRUE;
        END IF;
    END IF;
    
    -- 4. Check direct user permission
    SELECT 
        CASE p_permission
            WHEN 'view' THEN can_view
            WHEN 'edit' THEN can_edit
            WHEN 'delete' THEN can_delete
            WHEN 'share' THEN can_share
            ELSE FALSE
        END
    INTO has_direct_permission
    FROM nexus.dashboard_permissions
    WHERE dashboard_id = p_dashboard_id 
        AND user_id = p_user_id
        AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP);
    
    IF has_direct_permission THEN
        RETURN TRUE;
    END IF;
    
    -- 5. Check group-based permission
    SELECT 
        CASE p_permission
            WHEN 'view' THEN can_view
            WHEN 'edit' THEN can_edit
            WHEN 'delete' THEN can_delete
            WHEN 'share' THEN can_share
            ELSE FALSE
        END
    INTO has_group_permission
    FROM nexus.dashboard_permissions dp
    JOIN nexus.user_groups ug ON dp.group_id = ug.group_id
    WHERE dp.dashboard_id = p_dashboard_id 
        AND ug.user_id = p_user_id
        AND (dp.expires_at IS NULL OR dp.expires_at > CURRENT_TIMESTAMP)
    LIMIT 1;
    
    RETURN COALESCE(has_group_permission, FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function: Get all dashboards accessible by user with permissions
CREATE OR REPLACE FUNCTION nexus.get_user_dashboards(p_user_id UUID)
RETURNS TABLE (
    dashboard_id UUID,
    title VARCHAR,
    description TEXT,
    owner_user_id UUID,
    owner_username VARCHAR,
    is_public BOOLEAN,
    is_favorite BOOLEAN,
    tags JSONB,
    tile_count BIGINT,
    can_view BOOLEAN,
    can_edit BOOLEAN,
    can_delete BOOLEAN,
    can_share BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_accessed_at TIMESTAMP
) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT
        d.id,
        d.title,
        d.description,
        d.owner_user_id,
        u.username,
        d.is_public,
        d.is_favorite,
        d.tags,
        (SELECT COUNT(*) FROM nexus.dashboard_tiles dt WHERE dt.dashboard_id = d.id),
        nexus.user_has_dashboard_permission(p_user_id, d.id, 'view'),
        nexus.user_has_dashboard_permission(p_user_id, d.id, 'edit'),
        nexus.user_has_dashboard_permission(p_user_id, d.id, 'delete'),
        nexus.user_has_dashboard_permission(p_user_id, d.id, 'share'),
        d.created_at,
        d.updated_at,
        d.last_accessed_at
    FROM nexus.dashboards d
    LEFT JOIN nexus.users u ON d.owner_user_id = u.id
    WHERE 
        -- User is owner
        d.owner_user_id = p_user_id
        -- OR dashboard is public
        OR d.is_public = TRUE
        -- OR user has direct permission
        OR EXISTS (
            SELECT 1 FROM nexus.dashboard_permissions dp
            WHERE dp.dashboard_id = d.id 
                AND dp.user_id = p_user_id
                AND (dp.expires_at IS NULL OR dp.expires_at > CURRENT_TIMESTAMP)
        )
        -- OR user's group has permission
        OR EXISTS (
            SELECT 1 FROM nexus.dashboard_permissions dp
            JOIN nexus.user_groups ug ON dp.group_id = ug.group_id
            WHERE dp.dashboard_id = d.id 
                AND ug.user_id = p_user_id
                AND (dp.expires_at IS NULL OR dp.expires_at > CURRENT_TIMESTAMP)
        )
        -- OR user is admin/superadmin
        OR EXISTS (
            SELECT 1 FROM nexus.user_roles ur
            JOIN nexus.roles r ON ur.role_id = r.id
            WHERE ur.user_id = p_user_id 
                AND LOWER(r.name) IN ('admin', 'superadmin')
        )
    ORDER BY d.updated_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- 5. COMMENTS FOR DOCUMENTATION
-- =============================================================================

COMMENT ON TABLE nexus.dashboard_tiles IS 'Individual chart tiles/widgets within dashboards. Each tile represents one visualization.';
COMMENT ON TABLE nexus.dashboard_permissions IS 'Fine-grained RBAC for dashboards. Controls view/edit/delete/share permissions per user or group.';

COMMENT ON COLUMN nexus.dashboard_tiles.chart_type IS 'Plotly.js chart type. See constraint for full list of supported types.';
COMMENT ON COLUMN nexus.dashboard_tiles.chart_config IS 'Plotly-specific configuration (colors, axes labels, legend position, etc.)';
COMMENT ON COLUMN nexus.dashboard_tiles.refresh_interval_seconds IS 'Auto-refresh interval in seconds. NULL means manual refresh only.';
COMMENT ON COLUMN nexus.dashboard_tiles.position_x IS 'Grid column position (0-based). Used for dashboard layout.';
COMMENT ON COLUMN nexus.dashboard_tiles.width IS 'Grid column span (1-12). Uses 12-column grid system.';

COMMENT ON COLUMN nexus.dashboard_permissions.can_view IS 'Permission to view dashboard and its tiles';
COMMENT ON COLUMN nexus.dashboard_permissions.can_edit IS 'Permission to edit dashboard metadata and tiles';
COMMENT ON COLUMN nexus.dashboard_permissions.can_delete IS 'Permission to delete dashboard';
COMMENT ON COLUMN nexus.dashboard_permissions.can_share IS 'Permission to grant/revoke permissions to other users';
COMMENT ON COLUMN nexus.dashboard_permissions.expires_at IS 'Optional expiration for temporary access (e.g., guest access)';

COMMENT ON FUNCTION nexus.user_has_dashboard_permission IS 'Checks if user has specific permission on dashboard. Returns TRUE for owners and admins.';
COMMENT ON FUNCTION nexus.get_user_dashboards IS 'Returns all dashboards accessible by user with their permissions. Includes owned, public, and explicitly shared dashboards.';

-- =============================================================================
-- VERIFICATION
-- =============================================================================

SELECT 'Dashboard Tiles table created' AS status 
WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'nexus' AND table_name = 'dashboard_tiles');

SELECT 'Dashboard Permissions table created' AS status 
WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'nexus' AND table_name = 'dashboard_permissions');

SELECT 'RBAC helper functions created' AS status 
WHERE EXISTS (SELECT 1 FROM information_schema.routines WHERE routine_schema = 'nexus' AND routine_name = 'user_has_dashboard_permission');

