connector.name=postgresql
connection-url=jdbc:postgresql://postgres:5432/dashboard
connection-user=nexus_service
connection-password=PostgreActyze123$

# Connection pool settings
connection-pool.max-size=30
connection-pool.min-size=1

# Performance settings
postgresql.include-system-tables=false
postgresql.array-mapping=ARRAY
